# Header
# Docker compose syntax version
version: '3.8'

# List of containers
services:
  influxdb: # Service name (define by your self)
    image: influxdb:1.8 # (Docker image version pulled from Docker-hub)
    container_name: influxdb
    ports:
      - "${INFLUXDB_LOCAL_PORT}:8086"
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - ./influxdb/data:/var/lib/influxdb # Save data to local
    networks:
      - monitoring # If in the same network, 2 container can comnunicate

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "${GRAFANA_LOCAL_PORT}:3000"
    environment:
      # Grafana login
      - GRAFANA_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      # Pass variables to provisioning
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER} 
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD} 
      - INFLUXDB_DB=${INFLUXDB_DB} 
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - influxdb # !IMPORTANT: Run influxdb > Run grafana
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "${LOKI_LOCAL_PORT}:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
networks:
  monitoring: # Create network 'monitoring'
    driver: bridge # Default driver (containter in a network can ping each other)
    