apiVersion: 1 # Grafana provisioning API (default: 1)

datasources: # List of all datasources
  - name: InfluxDB # Name of datasource on Grafana UI
    type: influxdb # Datasource type
    access: proxy # Backend: Grafana calls influxDB
    url: http://influxdb:8086
    database: ${INFLUXDB_DB}

    # Login information
    user: ${INFLUXDB_ADMIN_USER}
    secureJsonData:
      password: ${INFLUXDB_ADMIN_PASSWORD}
    jsonData:
      httpMode: GET
    isDefault: true # True -> set as default datasource

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100